### ISSUE TITLE
Terraform module to Set the Export filters in chronicle in GCP.

### ISSUE THREAD

**Issue by itskkmgit** [GoogleCloudPlatform/security-analytics#14]
Is there any terraform- google module that can configure/set the 'Custom export filter settings' in chronicle. 
Kindly share any details around this.

**Comment by itskkmgit** [comment]
Do we have a terraform google module that can help to configure the filter conditions shown in the above screenshot?
Security --> Security Command Center --> Chronicle --> Export Filter settings

**Comment by rarsan** [comment]
Apologies. I assumed this was already answered.
There's currently no Chronicle API to manage export filter settings, so it's not possible to have a terraform module to configure these settings. We are tracking this feature request internally. Closing this ticket as this is out of scope of CSA solution, but I'll update this ticket if such Chronicle API becomes available.
