### ISSUE TITLE
Incorrect use of operator OR in file

### ISSUE THREAD

**Issue by tszebeni** [GoogleCloudPlatform/security-analytics#37]
Dear repo maintainers,
 while I was investigating the queries for log analytics, I found that there is an error in file:
https://github.com/GoogleCloudPlatform/security-analytics/blob/4e139fe1ac21745dcf4cf9c0f942dedda0c83817/backends/log_analytics/sql/1_30_console_accesses.sql#L34
comma needs to be used instead of an OR, within parentheses of operator IN.
That way the query succeeds, otherwise syntax error is given.

**Comment by rarsan** [comment]
Keeping this open for now until fix is in.

**Comment by rarsan** [comment]
Fixed with now-merged PR #35 ([commit](https://github.com/GoogleCloudPlatform/security-analytics/pull/35/commits/a576a64b4fe9d5e441280d2e83ea4cdffc8d736a))
