### ISSUE TITLE
CI/CD Readme file points to the wrong folder for Github action workflow

### ISSUE THREAD

**Issue by archyufa** [GoogleCloudPlatform/security-analytics#38]
Following [document](https://github.com/GoogleCloudPlatform/security-analytics/tree/main/cicd#using-in-a-github-actions-pipeline)

Suggest that the file should be placed in a `.github/workflow`, however correct folder should be `.github/workflows` for Github action pipeline to work properly.

**Comment by rarsan** [comment]
Thx for reporting this @archyufa - The broken link has been fixed, plus added a link to GitHub Actions docs. Cheers.
